### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by MitrandirToPP** [DeepSystems/supervisely-tutorials#1]
Got error in jupyter notebook script, in the very beginning

import keras
import tensorflow as tf
print('TensorFlow version:', tf.__version__)
print('Keras version:', keras.__version__)

Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28_pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

/opt/conda/lib/python3.5/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

/opt/conda/lib/python3.5/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343return _load(spec)
    344 

ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-15d3172afaf9> in <module>()
----> 1import keras
      2 import tensorflow as tf
      3 print('TensorFlow version:', tf.__version__)
      4 print('Keras version:', keras.__version__)

/src/keras/__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3from . import utils
      4 from . import activations
      5 from . import applications

/src/keras/utils/__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6from . import conv_utils
      7 
      8 # Globally-importable utils.

/src/keras/utils/conv_utils.py in <module>()
      1 from six.moves import range
      2 import numpy as np
----> 3from .. import backend as K
      4 
      5 

/src/keras/backend/__init__.py in <module>()
     81 elif _BACKEND == 'tensorflow':
     82     sys.stderr.write('Using TensorFlow backend.\n')
---> 83from .tensorflow_backend import *
     84 else:
     85     raise ValueError('Unknown backend: ' + str(_BACKEND))

/src/keras/backend/tensorflow_backend.py in <module>()
----> 1import tensorflow as tf
      2 from tensorflow.python.client import device_lib
      3 from tensorflow.python.training import moving_averages
      4 from tensorflow.python.ops import tensor_array_ops
      5 from tensorflow.python.ops import control_flow_ops

/opt/conda/lib/python3.5/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

/opt/conda/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72raise ImportError(msg)
     73 
     74 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/conda/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/conda/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

What have I done wrong?

**Comment by mkolomeychenko** [comment]
Do you have cuda libraries installed on your host? What is the version?

**Comment by Skywalker666666** [comment]
Hi, I got similiar problem with this. which feedback to me as:


---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-c555867334b8> in <module>()
      2 get_ipython().magic('matplotlib inline')
      3 import numpy as np
----> 4 import cv2
      5 from os.path import join
      6 import os

/usr/local/lib/python3.5/dist-packages/cv2/__init__.py in <module>()
      7 
      8 # make IDE's (PyCharm) autocompletion happy
----> 9 from .cv2 import *
     10 
     11 # wildcard import above does not import "private" variables like __version__

ImportError: libSM.so.6: cannot open shared object file: No such file or directory

In [ ]:

**Comment by Qirui-Y** [comment]
I had a similar problem before, maybe a version compatibility issue, re-created the virtual environment and don't install the tensorflow-gpu version if your computer performance is not good.
