### ISSUE TITLE
Getting error on when trying to run  OCR anpr_ocr

### ISSUE THREAD

**Issue by likwifi** [DeepSystems/supervisely-tutorials#26]
Getting following error when running command `jupyter notebook`

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1602, in initialize
    self.init_webapp()
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1354, in init_webapp
    self.jinja_environment_options,
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 275, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1042, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/opt/conda/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/opt/conda/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/conda/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/opt/conda/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/opt/conda/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/opt/conda/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/opt/conda/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/opt/conda/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/opt/conda/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

**Comment by likwifi** [comment]
It seems like this issue comes from parso.
By default vm installs python 3.5 however parso requires 3.6 when upgrading with conda install python=3.6 this seems to be fixed.
